### ISSUE TITLE
想要一份包含所有数据的数据包，大佬可以分享出来吗？

### ISSUE THREAD

**Issue by busyrat** [ppchart/ppchart#5]

**Comment by ppchart** [comment]
静态资源正在上传网盘，整理好了发给你发自我的iPhone------------------ 原始邮件 ------------------发件人: busyrat  ***@***.***>发送时间: 2022年2月11日 09:28收件人: ppchart/ppchart ***@***.***>抄送: Subscribed ***@***.***>主题: Re: [ppchart/ppchart] 想要一份包含所有数据的数据包，大佬可以分享出来吗？ (Issue #5)


—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ppchart/ppchart/issues/5",
"url": "https://github.com/ppchart/ppchart/issues/5",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ppchart** [comment]
静态资源正在上传网盘，整理好了我把网盘地址发在这里

**Comment by ppchart** [comment]
链接：https://pan.baidu.com/s/1F3I7FnTPfsE1YT8D2udBZg
提取码：star 

这个是所有示例的图片+依赖的静态资源，都打好压缩包在这里了

本来折腾用阿里云网盘，想着下载速度可以快一些，但阿里云网盘不支持分享压缩包文件

百度网盘将就下吧

**Comment by busyrat** [comment]
@ppchart 十分感谢

**Comment by langren1353** [comment]
感谢数据分享

**Comment by userlvjiajun** [comment]
大哥，找不到开发文档，有嘛？

**Comment by Wuguang11** [comment]
服务挂了吗

**Comment by yooyea** [comment]
> 服务挂了吗

不好意思，证书到期了，刚续费恢复了

**Comment by Sspphins** [comment]
服务挂了
